---
# tasks file for nextcloud
- name: Get moorea user info
  ansible.builtin.getent:
    database: passwd
    key: moorea
  tags: nextcloud

- name: Create directories
  ansible.builtin.file:
    path: /opt/nextcloud/mysql
    state: directory
    recurse: true
    owner: moorea
    group: moorea
  become: true
  tags: nextcloud

- name: Copy docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/nextcloud/docker-compose.yml
    mode: "644"
    owner: moorea
    group: moorea
  become: true
  tags: nextcloud

- name: Start nextcloud
  community.docker.docker_compose:
    project_src: /opt/nextcloud/
  become: true
  tags: nextcloud
