---
# tasks file for docker
- name: Install needed packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-docker
    state: present
    update_cache: true
  become: true
  tags: docker

- name: Add docker
  become: true
  tags: docker
  block:
    - name: Add GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: true
    - name: Change dns configuration
      ansible.builtin.lineinfile:
        path: /etc/default/docker
        line: DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
        state: present
    - name: Start docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
    - name: Start docker service
      ansible.builtin.service:
        name: containerd
        enabled: true
    - name: Create network
      community.docker.docker_network:
        name: services
