version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    networks:
      - "services"
    volumes:
      - ./data:/data
    labels:
      - com.centurylinklabs.watchtower.enable="true"
      - traefik.enable="true"
      - traefik.http.services.vault.loadbalancer.server.port="80"
      - traefik.http.services.vault-ws.loadbalancer.server.port="3012"
networks:
  services:
    external: true
    name: services
